### ISSUE TITLE
Support drop/Q key

### ISSUE THREAD

**Issue by tacotexmex** [mt-mods/controls#3]
This should be possible by adding a callback to whatever is already in `minetest.item_drop` from `minetest.register_on_mods_loaded`, yes?

**Comment by S-S-X** [comment]
Depends, `minetest.item_drop` is default but wont be called if item has `on_drop` defined.
If it should be actually for controls then `on_drop` needs override instead of `item_drop`.

**Comment by tacotexmex** [comment]
Oh, yes, I see. Overriding on_drop for every single item feels a wee bit hacky 🥲

**Comment by wsor4035** [comment]
seems doable, however probably would only be able to support it in the press api, since no way of knowing if its held/let off
